# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zturn_pins.xdc

# Block Designs: bd/DB/DB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB || ORIG_REF_NAME==DB} -quiet] -quiet

# IP: bd/DB/ip/DB_processing_system7_0_0/DB_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_processing_system7_0_0 || ORIG_REF_NAME==DB_processing_system7_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_dongbo_0_0/DB_dongbo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_dongbo_0_0 || ORIG_REF_NAME==DB_dongbo_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_clk_wiz_0_0/DB_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_clk_wiz_0_0 || ORIG_REF_NAME==DB_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_target_moving_0_0/DB_target_moving_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_target_moving_0_0 || ORIG_REF_NAME==DB_target_moving_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_xlconstant_0_0/DB_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_xlconstant_0_0 || ORIG_REF_NAME==DB_xlconstant_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_YK71_Tracker_AXI_0_0/DB_YK71_Tracker_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_YK71_Tracker_AXI_0_0 || ORIG_REF_NAME==DB_YK71_Tracker_AXI_0_0} -quiet] -quiet

# IP: bd/DB/ip/DB_axi_smc_0/DB_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_axi_smc_0 || ORIG_REF_NAME==DB_axi_smc_0} -quiet] -quiet

# IP: bd/DB/ip/DB_rst_ps7_0_250M_0/DB_rst_ps7_0_250M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_rst_ps7_0_250M_0 || ORIG_REF_NAME==DB_rst_ps7_0_250M_0} -quiet] -quiet

# IP: bd/DB/ip/DB_Target_Stationary_0_0/DB_Target_Stationary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DB_Target_Stationary_0_0 || ORIG_REF_NAME==DB_Target_Stationary_0_0} -quiet] -quiet

# XDC: f:/FPGA_Project/FPGA_YK71/YK71/YK71.gen/sources_1/bd/DB/DB_ooc.xdc
