# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FPGA_Project/FPGA_YK71/YK71/YK71.srcs/sources_1/bd/DB/ip/DB_processing_system7_0_0/DB_processing_system7_0_0.xci
# IP: The module: 'DB_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Project/FPGA_YK71/YK71/YK71.gen/sources_1/bd/DB/ip/DB_processing_system7_0_0/DB_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DB_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/FPGA_Project/FPGA_YK71/YK71/YK71.srcs/sources_1/bd/DB/ip/DB_processing_system7_0_0/DB_processing_system7_0_0.xci
# IP: The module: 'DB_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Project/FPGA_YK71/YK71/YK71.gen/sources_1/bd/DB/ip/DB_processing_system7_0_0/DB_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DB_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
