@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 23 10:28:46 +0700 2026
REM SW Build 6060944 on Thu Mar 06 19:10:01 MST 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim target_moving_tb_behav -key {Behavioral:sim_1:Functional:target_moving_tb} -tclbatch target_moving_tb.tcl -protoinst "protoinst_files/bd_dc1b.protoinst" -protoinst "protoinst_files/DB.protoinst" -view F:/FPGA_Project/FPGA_YK71/YK71/Sys_tb_behav.wcfg -log simulate.log"
call xsim  target_moving_tb_behav -key {Behavioral:sim_1:Functional:target_moving_tb} -tclbatch target_moving_tb.tcl -protoinst "protoinst_files/bd_dc1b.protoinst" -protoinst "protoinst_files/DB.protoinst" -view F:/FPGA_Project/FPGA_YK71/YK71/Sys_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
